import AuthProvider from "@/package/client/authProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Easy Next Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider userData='http://localhost:3000/api/me'>
      <html lang='en'>
        <body className={inter.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
